// AUTO-GENERATED BY bin/sync-twin.ts — DO NOT EDIT
// Source: packages/agent-registry/python/axis_agent_registry/assignments.py
// Regenerate with: npm run sync-twin
// Drift check:    npm run sync-twin:check

export const DEFAULT_ASSIGNMENTS: Record<string, string> = {
  "acknowledge_escalation": "openai/gpt-5.4-mini",
  "agentic_master": "openai/gpt-5.4-mini",
  "confirm_problem": "openai/gpt-5.4-mini",
  "critic": "openai/gpt-5.4-nano",
  "cross_conv_summary": "openai/gpt-5.4-nano",
  "general_default": "google/gemini-3.1-flash-lite",
  "greet": "openai/gpt-5.4-nano",
  "image_analyzer": "google/gemini-3.1-flash-lite",
  "intent_analyzer": "openai/gpt-5.4-nano",
  "resolution_tracker_llm": "openai/gpt-5.4-nano",
  "search_help_center": "openai/gpt-5.4-nano",
  "shift_report": "openai/gpt-5.4-nano",
};
