// AUTO-GENERATED BY bin/sync-twin.ts — DO NOT EDIT
// Source: packages/agent-registry/python/axis_agent_registry/catalog.py
// Regenerate with: npm run sync-twin
// Drift check:    npm run sync-twin:check
//
// Python snake_case -> TS camelCase mapping:
//   in_price_per_m  -> inPricePerM
//   out_price_per_m -> outPricePerM
//   ctx_tokens      -> ctxTokens
//   supports_tools  -> supportsTools
//   leak_risk       -> leakRisk

export interface ModelSpec {
  id: string;
  inPricePerM: number;
  outPricePerM: number;
  ctxTokens: number;
  supportsTools: boolean;
  released: string;
  family: string;
  notes: string;
  leakRisk: string;
}

export const CATALOG: Record<string, ModelSpec> = {
  "anthropic/claude-4.5-haiku": {
    id: "anthropic/claude-4.5-haiku",
    inPricePerM: 1,
    outPricePerM: 5,
    ctxTokens: 200000,
    supportsTools: true,
    released: "2025-10-15",
    family: "anthropic",
    notes: "Currently used by critic (langfuse default route). Expensive vs alternatives.",
    leakRisk: "low",
  },
  "deepseek/deepseek-v4-flash": {
    id: "deepseek/deepseek-v4-flash",
    inPricePerM: 0.14,
    outPricePerM: 0.28,
    ctxTokens: 1048576,
    supportsTools: true,
    released: "2026-04-23",
    family: "deepseek",
    notes: "Cheapest credible option. 1M context. Untested for Iris voice yet.",
    leakRisk: "low",
  },
  "deepseek/deepseek-v4-pro": {
    id: "deepseek/deepseek-v4-pro",
    inPricePerM: 0.43,
    outPricePerM: 0.87,
    ctxTokens: 1048576,
    supportsTools: true,
    released: "2026-04-23",
    family: "deepseek",
    notes: "Mid-tier DeepSeek. Reasoning toggle.",
    leakRisk: "low",
  },
  "google/gemini-3.1-flash-lite": {
    id: "google/gemini-3.1-flash-lite",
    inPricePerM: 0.25,
    outPricePerM: 1.5,
    ctxTokens: 1048576,
    supportsTools: true,
    released: "2026-05-07",
    family: "google",
    notes: "Multimodal (vision). Clean tools in test. Good for image_analyzer.",
    leakRisk: "low",
  },
  "moonshotai/kimi-k2-0905": {
    id: "moonshotai/kimi-k2-0905",
    inPricePerM: 0.4,
    outPricePerM: 2,
    ctxTokens: 262144,
    supportsTools: true,
    released: "2025-09-04",
    family: "kimi",
    notes: "Confirmed tool-format leak under large prompts (SOUL+13 tools+history). Emits raw 'send_message_to_customer:N{...}' as content intermittently. 2026-05-10 incident.",
    leakRisk: "high",
  },
  "moonshotai/kimi-k2.6": {
    id: "moonshotai/kimi-k2.6",
    inPricePerM: 0.75,
    outPricePerM: 3.5,
    ctxTokens: 262144,
    supportsTools: true,
    released: "2026-04-20",
    family: "kimi",
    notes: "Newer Kimi. Tool calling clean in tests but ~14s latency.",
    leakRisk: "low",
  },
  "openai/gpt-5.4-mini": {
    id: "openai/gpt-5.4-mini",
    inPricePerM: 0.75,
    outPricePerM: 4.5,
    ctxTokens: 400000,
    supportsTools: true,
    released: "2026-03-17",
    family: "openai",
    notes: "Currently default for supervisor chat. Tool calling reliable. Output usually short -> real cost low.",
    leakRisk: "low",
  },
  "openai/gpt-5.4-nano": {
    id: "openai/gpt-5.4-nano",
    inPricePerM: 0.2,
    outPricePerM: 1.25,
    ctxTokens: 400000,
    supportsTools: true,
    released: "2026-03-17",
    family: "openai",
    notes: "Cheaper sibling of gpt-5.4-mini. Useful for intent_analyzer / critic.",
    leakRisk: "low",
  },
  "qwen/qwen3.6-flash": {
    id: "qwen/qwen3.6-flash",
    inPricePerM: 0.25,
    outPricePerM: 1.5,
    ctxTokens: 1000000,
    supportsTools: true,
    released: "2026-04-26",
    family: "qwen",
    notes: "Alibaba. Strong Spanish. Untested for Iris.",
    leakRisk: "low",
  },
};
