/**
 * TypeScript twin of axis_agent_registry.registry.
 *
 * Hand-written (NOT generated). Mirrors the Python resolution logic in
 * registry.py exactly. The 10-pair snapshot test asserts byte-for-byte
 * parity vs Python's get_model_for.
 *
 * Resolution order for getModelFor(role, opts?):
 *   1. opts.envOverrides[ROLE_UPPER] (test/sync-twin injection)
 *   2. process.env[`${prefix}${ROLE_UPPER}`] for each OVERRIDE_PREFIXES
 *      in priority order (AXIS first, INVIDIA second)
 *   3. opts.hybridCrmLookup or module-level setHybridCrmOverrideLookup hook
 *   4. DEFAULT_ASSIGNMENTS static fallback
 *
 * Unknown override model ids in any layer: console.warn + fall through.
 * Unknown role: throw Error. Role mapped to model not in CATALOG: throw.
 *
 * Source of truth for the data layer is Python; catalog.ts + assignments.ts
 * are AUTO-GENERATED by bin/sync-twin.ts.
 */
import { DEFAULT_ASSIGNMENTS } from "./assignments.js";
import { CATALOG, type ModelSpec } from "./catalog.js";

// ---------------------------------------------------------------------------
// Public constants
// ---------------------------------------------------------------------------

/**
 * Env var prefixes in priority order. AXIS is canonical (new ecosystem);
 * INVIDIA is legacy (existing Sophie Railway env). When both are set for
 * the same role, AXIS wins.
 *
 * MUST match the Python OVERRIDE_PREFIXES tuple byte-for-byte.
 */
export const OVERRIDE_PREFIXES = [
  "AXIS_MODEL_OVERRIDE_",
  "INVIDIA_MODEL_OVERRIDE_",
] as const;

// ---------------------------------------------------------------------------
// Hybrid-CRM override injection seam
// ---------------------------------------------------------------------------

type HybridCrmLookup = (role: string) => string | null | undefined;

let hybridCrmLookup: HybridCrmLookup | null = null;

/**
 * Register (or clear, with null) a callback returning the hybrid-crm UI
 * override for a role. Called once at host import time (analogous to the
 * Python shim wiring set_hybrid_crm_override_lookup).
 *
 * Contract:
 *   - fn(role_lower) -> model_id (string) or null/undefined
 *   - fn MUST NOT raise; any exception is caught and treated as null
 *   - fn is consulted only when no env override matched
 */
export function setHybridCrmOverrideLookup(fn: HybridCrmLookup | null): void {
  hybridCrmLookup = fn;
}

// ---------------------------------------------------------------------------
// Public types
// ---------------------------------------------------------------------------

export interface GetModelForOptions {
  /**
   * Explicit map of UPPERCASE role names -> model id. Takes precedence
   * over process.env. Used by tests and the sync-twin snapshot fixture
   * to inject overrides deterministically.
   */
  envOverrides?: Record<string, string>;
  /**
   * Per-call hybrid-crm lookup callback. Falls back to the module-level
   * hook set by setHybridCrmOverrideLookup. Same return contract.
   */
  hybridCrmLookup?: HybridCrmLookup;
}

// ---------------------------------------------------------------------------
// Resolution helpers
// ---------------------------------------------------------------------------

function resolveExplicit(
  roleUpper: string,
  envOverrides: Record<string, string> | undefined,
): string | null {
  if (!envOverrides) return null;
  const candidate = envOverrides[roleUpper];
  if (!candidate) return null;
  if (!(candidate in CATALOG)) {
    console.warn(
      `axis-agent-registry: explicit envOverrides[${roleUpper}]=${candidate} ` +
        `NOT in catalog — ignoring and falling back`,
    );
    return null;
  }
  return candidate;
}

function resolveEnvPrefix(roleUpper: string): string | null {
  for (const prefix of OVERRIDE_PREFIXES) {
    const envKey = `${prefix}${roleUpper}`;
    const raw = process.env[envKey];
    const value = (raw ?? "").trim();
    if (!value) continue;
    if (!(value in CATALOG)) {
      console.warn(
        `axis-agent-registry: env override ${envKey}=${value} ` +
          `NOT in catalog — ignoring and falling back`,
      );
      continue;
    }
    return value;
  }
  return null;
}

function resolveHybridCrm(
  roleLower: string,
  perCallLookup: HybridCrmLookup | undefined,
): string | null {
  const fn = perCallLookup ?? hybridCrmLookup;
  if (!fn) return null;
  let candidate: string | null | undefined;
  try {
    candidate = fn(roleLower);
  } catch (err) {
    console.warn(
      `axis-agent-registry: hybrid-crm lookup threw for role=${roleLower} ` +
        `— falling through to defaults (${(err as Error).message})`,
    );
    return null;
  }
  if (!candidate) return null;
  if (!(candidate in CATALOG)) {
    console.warn(
      `axis-agent-registry: hybrid-crm UI override role=${roleLower} ` +
        `model=${candidate} NOT in catalog — ignoring and falling back`,
    );
    return null;
  }
  return candidate;
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Return the model id assigned to a role, applying the override chain.
 *
 * @throws Error if `role` is unknown (not in DEFAULT_ASSIGNMENTS), or if
 *               the assigned model is not in CATALOG.
 */
export function getModelFor(role: string, opts?: GetModelForOptions): string {
  const roleLower = role.toLowerCase();
  const roleUpper = roleLower.toUpperCase();

  const explicit = resolveExplicit(roleUpper, opts?.envOverrides);
  if (explicit) return explicit;

  const envVal = resolveEnvPrefix(roleUpper);
  if (envVal) return envVal;

  const crmVal = resolveHybridCrm(roleLower, opts?.hybridCrmLookup);
  if (crmVal) return crmVal;

  const fallback = DEFAULT_ASSIGNMENTS[roleLower];
  if (!fallback) {
    throw new Error(
      `axis-agent-registry: unknown role=${JSON.stringify(role)}. ` +
        `Add it to DEFAULT_ASSIGNMENTS first.`,
    );
  }
  if (!(fallback in CATALOG)) {
    throw new Error(
      `axis-agent-registry: role=${JSON.stringify(role)} assigned to ` +
        `unregistered model=${JSON.stringify(fallback)}. Add it to CATALOG first.`,
    );
  }
  return fallback;
}

/**
 * Return the ModelSpec for a registered model id, or undefined if unknown.
 */
export function getSpec(modelId: string): ModelSpec | undefined {
  return CATALOG[modelId];
}

/**
 * Diagnostic dump — every role's resolved model + spec snapshot.
 *
 * Shape mirrors the Python `all_assignments()` output (snake_case-equivalent
 * fields in camelCase TS idiom). `fromOverride` is true iff ANY env prefix
 * supplied a value for that role at call time.
 */
export function allAssignments(): Record<
  string,
  {
    modelId: string;
    fromOverride: boolean;
    inPricePerM: number | null;
    outPricePerM: number | null;
    supportsTools: boolean | null;
    leakRisk: string | null;
    released: string | null;
  }
> {
  const out: Record<
    string,
    {
      modelId: string;
      fromOverride: boolean;
      inPricePerM: number | null;
      outPricePerM: number | null;
      supportsTools: boolean | null;
      leakRisk: string | null;
      released: string | null;
    }
  > = {};
  for (const role of Object.keys(DEFAULT_ASSIGNMENTS)) {
    const mid = getModelFor(role);
    const spec = CATALOG[mid];
    const roleUpper = role.toUpperCase();
    const fromOverride = OVERRIDE_PREFIXES.some(
      (prefix) => !!process.env[`${prefix}${roleUpper}`],
    );
    out[role] = {
      modelId: mid,
      fromOverride,
      inPricePerM: spec ? spec.inPricePerM : null,
      outPricePerM: spec ? spec.outPricePerM : null,
      supportsTools: spec ? spec.supportsTools : null,
      leakRisk: spec ? spec.leakRisk : null,
      released: spec ? spec.released : null,
    };
  }
  return out;
}

/**
 * Convenience alias for ergonomic Phase 2 imports:
 *
 *   import { DEFAULT_MODEL_FOR } from '@axis/agent-registry';
 *   const model = DEFAULT_MODEL_FOR('agentic_master');
 *
 * Identical to `getModelFor` (referentially equal by design — test 11
 * asserts this).
 */
export const DEFAULT_MODEL_FOR = getModelFor;
